### ISSUE TITLE
Falta el return False en el método __eq__

### ISSUE THREAD

**Issue by jpablohagata** [FIUBA-Posgrado-Inteligencia-Artificial/intro_ia#9]
En la comparación realizada en \_\_eq\_\_, solo se devuelve True cuando se cumple la condición; sin embargo, al final del método no se devuelve False.

https://github.com/FIUBA-Posgrado-Inteligencia-Artificial/intro_ia/blob/06afd57712d03dcf53f0f6477d57cfa1de358449/clase2/hanoi_tower/hanoi_states.py#L88

**Comment by facundolucianna** [comment]
Gracias por reportar el bug, ahi lo corregi en commit 05f0005
